/*
  EjmapExposure.h

  ejmap's re-implementation of the SERVER's controls-exposure build
  (echojay-saas-dialable lib/params-lib.js buildControlsRegistryEntry +
  lib/controls-note.js pool rule, at serverCommit 55af972). It exists so the
  tier preview card shows the mapper the EXACT twelve the server would
  expose, in the server's real order -- or the human corrects a list nobody
  sees.

  THE PIN: spec/controls-exposure-fixture.json carries the server's own
  output for both live maps, generated by a DIFFERENT program from prod
  data. The drift gate asserts this implementation reproduces it
  byte-identically (names, classes, trust, kinds, indices, the default
  twelve, the counts). Drift on either side fails the test and names the
  side that moved. Never "fix" a pin failure by editing this file to match
  intuition: read the fixture's serverCommit and diff the server first.

  Faithfulness notes (each mirrors a server line, not a preference):
  - class regexes run over the LOWERCASED name, ECMAScript semantics
  - case collisions (names equal lowercased): BOTH leave candidates and
    inventory, neither wins
  - lockstep_of present -> excluded from pool AND inventory, counted
  - a control whose index appears in any group -> band duplicate, excluded
  - sort: tier(primary first) > trust(human-verified > setread >
    llm-classified > unknown) > kind(anchored first) > vendor index asc
    (missing index sorts last)
  - default pool: plumbing NEVER; (musical && tier != hidden) or
    tier == primary; first K = 12 in order
*/

#pragma once

#include <juce_core/juce_core.h>
#include <map>
#include <regex>
#include <set>

namespace ejmap
{

struct Exposure
{
    static constexpr int kPerPlugin = 12;   // server K_PER_PLUGIN

    /** classifyControl, params-lib.js@55af972, byte-faithful. Applied to the
        lowercased name. The server's own caveats apply here too: "Power Soak"
        is musical (power counts only exact/trailing), "Quality Factor" is Q
        not render quality, "Cutoff 2" is not guarded by the on/off/in rule.
    */
    static juce::String classifyControl (const juce::String& name)
    {
        const std::string n = name.toLowerCase().toStdString();
        static const std::regex audition  (R"(\b(delta|solo|listen|monitor(ing)?|audition)\b)");
        static const std::regex plumbing1 (R"(\b(oversampl\w*|resolution|latency|tmt|bank|window|gui|ui)\b)");
        static const std::regex plumbing2 (R"(param\s*link|stereo\s*link|stereo\s*mode|link\s*mode|\blink\b)");
        static const std::regex guarded1  (R"(\b(bypass|enabled?|active)\b)");
        static const std::regex guarded2  (R"(\b(power|pwr)$)");
        static const std::regex cutoffEx  (R"(cut[\s-]?off\s*\d*$)");
        static const std::regex onOffIn   (R"(\b(on|off|in)\s*\d*$)");

        if (std::regex_search (n, audition))  return "audition";
        if (std::regex_search (n, plumbing1)
             || std::regex_search (n, plumbing2)) return "plumbing";
        if (std::regex_search (n, guarded1)
             || std::regex_search (n, guarded2)
             || (! std::regex_search (n, cutoffEx) && std::regex_search (n, onOffIn)))
            return "guarded";
        return "musical";
    }

    struct Candidate
    {
        juce::String name, kind, cls, trust, tier;
        int index = -1;
    };

    struct Result
    {
        juce::Array<Candidate> orderedCandidates;
        juce::StringArray defaultExposure;          // first K pool names, in order
        juce::StringArray excludedNames;            // with reasons, parallel
        juce::StringArray excludedReasons;
        int lockstepTwins = 0, bandDuplicates = 0, caseCollisions = 0;
    };

    /** The registry-entry build, over the EMITTED var shapes (map.controls
        object + map.groups array) so the preview and the conformance pin run
        the same bytes the server ingests.
    */
    static Result build (const juce::var& controlsVar, const juce::var& groupsVar)
    {
        Result r;
        auto* co = controlsVar.getDynamicObject();
        if (co == nullptr) return r;

        // Case collisions: lowercased name equality, both sides leave.
        std::map<juce::String, int> lowerCount;
        for (auto& kv : co->getProperties())
            ++lowerCount[kv.name.toString().toLowerCase()];

        // Band duplicates: indices claimed by any group member.
        std::set<int> groupIdx;
        if (auto* ga = groupsVar.getArray())
            for (auto& gv : *ga)
                if (auto* po = gv.getProperty ("params", juce::var()).getDynamicObject())
                    for (auto& pkv : po->getProperties())
                    {
                        const int gi = (int) pkv.value.getProperty ("index", -1);
                        if (gi >= 0) groupIdx.insert (gi);
                    }

        for (auto& kv : co->getProperties())
        {
            const auto nm = kv.name.toString();
            if (lowerCount[nm.toLowerCase()] > 1)
            { ++r.caseCollisions;
              r.excludedNames.add (nm); r.excludedReasons.add ("case collision: unresolvable address"); continue; }
            if (! kv.value.getProperty ("lockstep_of", juce::var()).isVoid())
            { ++r.lockstepTwins;
              r.excludedNames.add (nm); r.excludedReasons.add ("lockstep twin of ["
                  + kv.value.getProperty ("lockstep_of", juce::var()).toString() + "]"); continue; }
            const int idx = (int) kv.value.getProperty ("index", -1);
            if (idx >= 0 && groupIdx.count (idx) > 0)
            { ++r.bandDuplicates;
              r.excludedNames.add (nm); r.excludedReasons.add ("band duplicate: index in a group"); continue; }

            Candidate c;
            c.name  = nm;
            c.kind  = kv.value.getProperty ("kind", "").toString();
            c.cls   = classifyControl (nm);
            c.trust = kv.value.getProperty ("trust", "").toString();
            c.tier  = kv.value.getProperty ("tier", "").toString();
            c.index = idx;
            r.orderedCandidates.add (c);
        }

        std::stable_sort (r.orderedCandidates.begin(), r.orderedCandidates.end(),
            [] (const Candidate& a, const Candidate& b)
            {
                auto tierKey  = [] (const Candidate& c) { return c.tier == "primary" ? 0 : 1; };
                auto trustKey = [] (const Candidate& c)
                {
                    if (c.trust == "human-verified") return 0;
                    if (c.trust == "setread")        return 1;
                    if (c.trust == "llm-classified") return 2;
                    return 3;
                };
                auto kindKey  = [] (const Candidate& c) { return c.kind == "anchored" ? 0 : 1; };
                auto idxKey   = [] (const Candidate& c) { return c.index >= 0 ? c.index : 1000000000; };
                if (tierKey (a)  != tierKey (b))  return tierKey (a)  < tierKey (b);
                if (trustKey (a) != trustKey (b)) return trustKey (a) < trustKey (b);
                if (kindKey (a)  != kindKey (b))  return kindKey (a)  < kindKey (b);
                return idxKey (a) < idxKey (b);
            });

        for (const auto& c : r.orderedCandidates)
        {
            if (r.defaultExposure.size() >= kPerPlugin) break;
            if (c.cls == "plumbing") continue;
            const bool inPool = (c.cls == "musical" && c.tier != "hidden") || c.tier == "primary";
            if (inPool) r.defaultExposure.add (c.name);
        }
        return r;
    }
};

} // namespace ejmap
