/*
  EjmapNameTokens.h

  A PORT, NOT A RE-DERIVATION, of the server's name matcher: controlNameTokens and
  controlAnswersTerm in echojay-saas lib/controls-note.js (origin/main a86dba8). Roles
  (EjmapRoles.h) are decided with it, and the server already reads control names with it,
  so the two ends must not disagree about what a name says.

  Both copies are pinned to ONE vector file, tools/ejmap/tests/fixtures/name-token-vectors.json,
  generated by running the server's functions unmodified in node. RoundTripTest asserts this
  port against every vector; the server asserting the same file against its copy is a
  server-half item. Change the behaviour here only by changing the server first and
  regenerating the vectors.

  The JavaScript, and what each step here reproduces exactly:
    controlNameTokens(s) = String(s)
        .replace(/([a-z])([A-Z])/g, "$1 $2")     one pass each, left to right; only a
        .replace(/([A-Za-z])(\d)/g, "$1 $2")     lower->Upper change splits, so "aBcD" is
        .replace(/(\d)([A-Za-z])/g, "$1 $2")     a|bc|d. (A match consumes both characters,
                                                 as the regex does; in these three patterns
                                                 the second character can never start
                                                 another match, so that is not observable -
                                                 the 29 Sep mutation run confirmed it.)
        .toLowerCase().match(/[a-z0-9]+/g) || []
    controlAnswersTerm(name, term): the term, squashed to [a-z0-9], must EQUAL a contiguous
        run of the name's tokens ("hold" does not answer "Threshold", "ratio" does not
        answer "Calibration"); failing that, a BAND_ABBREV term answers a \b-bounded
        abbreviation in the lowercased name.

  JavaScript lowercasing is Unicode, but only [a-z0-9] survive tokenising and the regexes
  here have no u flag (\b and \w are ASCII). Exactly two non-ASCII code points lowercase to
  ASCII word characters (enumerated over all of Unicode in node, 29 Sep): U+0130 -> "i" +
  U+0307, and U+212A (Kelvin sign) -> "k". jsLower reproduces those two; every other
  non-ASCII character stays non-word, as it does on the server. So "Ärger" tokenises "rger",
  as the server's does - the quirk is carried, not fixed.
*/

#pragma once

#include <juce_core/juce_core.h>

namespace ejmap::nametokens
{

inline bool isLowerAscii (juce::juce_wchar c) { return c >= 'a' && c <= 'z'; }
inline bool isUpperAscii (juce::juce_wchar c) { return c >= 'A' && c <= 'Z'; }
inline bool isLetterAscii (juce::juce_wchar c) { return isLowerAscii (c) || isUpperAscii (c); }
inline bool isDigitAscii (juce::juce_wchar c) { return c >= '0' && c <= '9'; }
inline bool isTokenChar (juce::juce_wchar c) { return isLowerAscii (c) || isDigitAscii (c); }
// JavaScript's non-unicode \w, which is what \b tests
inline bool isJsWordChar (juce::juce_wchar c) { return isLetterAscii (c) || isDigitAscii (c) || c == '_'; }

using Chars = std::vector<juce::juce_wchar>;

inline Chars toChars (const juce::String& s)
{
    Chars out;
    for (auto p = s.getCharPointer(); ! p.isEmpty();)
        out.push_back (p.getAndAdvance());
    return out;
}

// One global String.replace(/(A)(B)/g, "$1 $2"): a match consumes both characters.
template <typename P1, typename P2>
Chars splitPass (const Chars& s, P1 first, P2 second)
{
    Chars out;
    out.reserve (s.size() * 2);
    size_t i = 0;
    while (i < s.size())
    {
        if (i + 1 < s.size() && first (s[i]) && second (s[i + 1]))
        {
            out.push_back (s[i]);
            out.push_back (' ');
            out.push_back (s[i + 1]);
            i += 2;
        }
        else
        {
            out.push_back (s[i]);
            ++i;
        }
    }
    return out;
}

// String.prototype.toLowerCase, as far as anything downstream can see (see the header).
inline Chars jsLower (const Chars& s)
{
    Chars out;
    out.reserve (s.size());
    for (auto c : s)
    {
        if (isUpperAscii (c))      out.push_back (c + ('a' - 'A'));
        else if (c == 0x0130)      { out.push_back ('i'); out.push_back (0x0307); }
        else if (c == 0x212A)      out.push_back ('k');
        else                       out.push_back (c);
    }
    return out;
}

inline juce::StringArray controlNameTokens (const juce::String& name)
{
    auto s = toChars (name);
    s = splitPass (s, isLowerAscii, isUpperAscii);
    s = splitPass (s, isLetterAscii, isDigitAscii);
    s = splitPass (s, isDigitAscii, isLetterAscii);
    s = jsLower (s);

    juce::StringArray tokens;
    juce::String run;
    for (auto c : s)
    {
        if (isTokenChar (c)) run += juce::String::charToString (c);
        else if (run.isNotEmpty()) { tokens.add (run); run.clear(); }
    }
    if (run.isNotEmpty()) tokens.add (run);
    return tokens;
}

// squashSeparators: lowercase, keep [a-z0-9]
inline juce::String squashSeparators (const juce::String& s)
{
    juce::String out;
    for (auto c : jsLower (toChars (s)))
        if (isTokenChar (c)) out += juce::String::charToString (c);
    return out;
}

// BAND_ABBREV, keyed on the RAW term (the server does Map.get(term), not a squashed term)
inline const std::vector<std::pair<juce::String, juce::StringArray>>& bandAbbrev()
{
    static const std::vector<std::pair<juce::String, juce::StringArray>> table {
        { "low",       { "lf" } },
        { "high",      { "hf" } },
        { "mid",       { "mf", "lmf", "hmf" } },
        { "low mid",   { "lmf" } },
        { "high mid",  { "hmf" } },
        { "low pass",  { "lp", "lpf" } },
        { "high pass", { "hp", "hpf" } },
        { "low cut",   { "hp", "hpf" } },
        { "high cut",  { "lp", "lpf" } },
    };
    return table;
}

// new RegExp("\\b" + word + "\\b").test(lowered), for a word of ASCII letters
inline bool jsWordBoundedContains (const Chars& lowered, const juce::String& word)
{
    const auto w = toChars (word);
    if (w.empty() || w.size() > lowered.size()) return false;
    for (size_t i = 0; i + w.size() <= lowered.size(); ++i)
    {
        if (! std::equal (w.begin(), w.end(), lowered.begin() + (long) i)) continue;
        const bool leftOk  = i == 0 || ! isJsWordChar (lowered[i - 1]);
        const bool rightOk = i + w.size() == lowered.size() || ! isJsWordChar (lowered[i + w.size()]);
        if (leftOk && rightOk) return true;
    }
    return false;
}

inline bool controlAnswersTerm (const juce::String& name, const juce::String& term)
{
    const auto t = squashSeparators (term);
    if (t.isNotEmpty())
    {
        const auto toks = controlNameTokens (name);
        for (int i = 0; i < toks.size(); ++i)
        {
            juce::String acc;
            for (int j = i; j < toks.size(); ++j)
            {
                acc += toks[j];
                if (acc == t) return true;
                if (acc.length() > t.length()) break;
            }
        }
    }
    for (const auto& [key, abbrevs] : bandAbbrev())
    {
        if (key != term) continue;
        const auto lowered = jsLower (toChars (name));
        for (const auto& a : abbrevs)
            if (jsWordBoundedContains (lowered, a)) return true;
        return false;
    }
    return false;
}

} // namespace ejmap::nametokens
