/*
    Project art parity self-test: ProjectArt::derive must agree with
    public/js/art-core.js in the echojay-saas repo.

    WHY. The same art_seed has to render the same tile on the web and in the
    plugin. Two implementations of one algorithm drift silently: the ORDER of
    PRNG calls IS the algorithm, so inserting or reordering one call on either
    side changes every tile on that side only, and nobody notices for months.
    This is the only thing that catches it.

    WHAT IT REPLACES. The specs claimed the port was "validated against a
    505-seed parity fixture with zero mismatches". That run happened once, in
    a throwaway harness in a container that no longer exists, and the fixture
    that shipped held ten entries rounded to 4dp. Neither could be re-run and
    the rounding hid the very difference worth detecting.

    THE FIXTURE IS GENERATED BY THE WEB REPO, by
    scripts/gen-art-parity-fixture.mjs, and copied here. That direction
    matters: art-core.js is normative and this side has to agree with it. A
    fixture generated here would only prove this side agrees with itself.

    TOLERANCE, stated rather than implied. JavaScript computes in double;
    ProjectArt carries results in float. The two part company around the
    seventh significant digit, so the float comparisons use an absolute
    epsilon of 1e-4, which is far tighter than any visible difference (a hue
    is in degrees, a coordinate is a fraction of a tile) and far looser than
    float32 noise.

    hueAnchor and blobCount are compared EXACTLY, with no tolerance. They are
    integers derived through floor(), so a disagreement means the two sides
    took different branches, not that they rounded differently, and the tile
    would differ structurally. If those ever fail, the algorithms really have
    diverged.
*/

#include <JuceHeader.h>
#include "ProjectArt.h"

#include <cstdio>
#include <cmath>

namespace
{
/** Absolute tolerance for values JS computed in double and C++ in float. */
constexpr double kEps = 1e-4;

int failures = 0;
int compared = 0;

void fail (const juce::String& what, const juce::String& seed, double expected, double actual)
{
    if (failures < 12) // enough to diagnose, not a wall of text
        std::printf ("  FAIL  %s  seed=%s  js=%.9f  cpp=%.9f  delta=%.3g\n",
                     what.toRawUTF8(), seed.toRawUTF8(), expected, actual,
                     std::abs (expected - actual));
    ++failures;
}

void closeEnough (const juce::String& what, const juce::String& seed, double js, double cpp)
{
    ++compared;
    if (std::abs (js - cpp) > kEps)
        fail (what, seed, js, cpp);
}

void exact (const juce::String& what, const juce::String& seed, double js, double cpp)
{
    ++compared;
    if (js != cpp)
        fail (what, seed, js, cpp);
}
} // namespace

int main (int argc, char** argv)
{
    const juce::String path = argc > 1 ? juce::String (argv[1])
                                       : juce::String ("tools/art_parity_test/art-parity.json");
    const juce::File file (juce::File::getCurrentWorkingDirectory().getChildFile (path));
    if (! file.existsAsFile())
    {
        std::printf ("art_parity_test: FIXTURE NOT FOUND at %s\n",
                     file.getFullPathName().toRawUTF8());
        return 1;
    }

    const auto root = juce::JSON::parse (file);
    const auto* obj = root.getDynamicObject();
    if (obj == nullptr)
    {
        std::printf ("art_parity_test: fixture is not a JSON object\n");
        return 1;
    }

    const auto casesVar = obj->getProperty ("cases");
    const auto* cases = casesVar.getArray();
    if (cases == nullptr || cases->isEmpty())
    {
        std::printf ("art_parity_test: fixture has no cases\n");
        return 1;
    }

    std::printf ("art parity self-test: %d cases from %s\n",
                 cases->size(), file.getFileName().toRawUTF8());

    juce::SortedSet<int> blobCountsSeen;

    for (const auto& cv : *cases)
    {
        const auto* c = cv.getDynamicObject();
        if (c == nullptr) { ++failures; continue; }

        const juce::String seed = c->getProperty ("seed").toString();
        const auto p = echojay::ProjectArt::derive (seed);

        exact ("hueAnchor", seed, (double) (int) c->getProperty ("hueAnchor"), (double) p.hueAnchor);
        closeEnough ("spread", seed, (double) c->getProperty ("spread"), (double) p.spread);

        const int jsBlobCount = (int) c->getProperty ("blobCount");
        exact ("blobCount", seed, (double) jsBlobCount, (double) p.blobs.size());
        blobCountsSeen.add (jsBlobCount);

        // The base colour is derived, not random, but it is what fills the
        // tile behind every blob so a mismatch is a solid-colour difference.
        if (const auto* base = c->getProperty ("base").getDynamicObject())
        {
            closeEnough ("base.h", seed, (double) base->getProperty ("h"), (double) p.baseH);
            closeEnough ("base.s", seed, (double) base->getProperty ("s"), (double) p.baseS);
            closeEnough ("base.l", seed, (double) base->getProperty ("l"), (double) p.baseL);
        }

        const auto* blobs = c->getProperty ("blobs").getArray();
        if (blobs == nullptr || blobs->size() != p.blobs.size()) { ++failures; continue; }

        for (int i = 0; i < blobs->size(); ++i)
        {
            const auto* b = (*blobs)[i].getDynamicObject();
            if (b == nullptr) { ++failures; continue; }
            const auto& g = p.blobs.getReference (i);
            const auto tag = seed + "[" + juce::String (i) + "]";
            closeEnough ("blob.h",  tag, (double) b->getProperty ("h"),  (double) g.h);
            closeEnough ("blob.s",  tag, (double) b->getProperty ("s"),  (double) g.s);
            closeEnough ("blob.l",  tag, (double) b->getProperty ("l"),  (double) g.l);
            closeEnough ("blob.cx", tag, (double) b->getProperty ("cx"), (double) g.cx);
            closeEnough ("blob.cy", tag, (double) b->getProperty ("cy"), (double) g.cy);
            closeEnough ("blob.r",  tag, (double) b->getProperty ("r"),  (double) g.r);
        }
    }

    // A fixture that missed a blob count would leave a branch of the derive
    // loop unchecked. The generator asserts this too; asserted again here so
    // a hand-trimmed fixture cannot quietly weaken the test.
    for (int n : { 4, 5, 6 })
        if (! blobCountsSeen.contains (n))
        {
            std::printf ("  FAIL  fixture covers no case with blobCount %d\n", n);
            ++failures;
        }

    std::printf ("  %d value comparisons, tolerance %.0e (integers exact)\n", compared, kEps);

    if (failures)
    {
        std::printf ("art_parity_test: %d FAILED\n", failures);
        std::printf ("  The plugin and the web now draw different tiles for the same seed.\n");
        std::printf ("  Check the ORDER of rng calls in ProjectArt::derive against\n");
        std::printf ("  public/js/art-core.js deriveArt, then regenerate the fixture.\n");
        return 1;
    }

    std::printf ("art_parity_test: PASS\n");
    return 0;
}
