#pragma once

#include <JuceHeader.h>
#include "EJPlaybackArt.h"       // generated by juce_add_binary_data(EchoJayPlaybackArt)
#include "EJPlaybackVoicing.h"   // echojay::PlaybackVoicing
#include "EJPlaybackTiles.h"     // echojay::PlaybackTile, the grid's rows

// =============================================================================
//  PLAYBACK ART: which picture belongs to which voicing and which codec tile.
// =============================================================================
//
// The nineteen images in Assets/playback are compiled into their own static
// library, EchoJayPlaybackArt, by juce_add_binary_data in CMakeLists.txt, with
// a named header and namespace (EJPlaybackArt.h, EJPlaybackArt::) so JUCE's
// default BinaryData.h is not included into every translation unit through
// JuceHeader.h. Each file is a symbol named after it: bedroom.jpg becomes
// EJPlaybackArt::bedroom_jpg and EJPlaybackArt::bedroom_jpgSize.
//
// WHO MAY INCLUDE THIS. Only translation units of the EchoJay target. The
// generated header's folder reaches EchoJay's include path because that target
// links the library; nothing else does. In particular mapfps_test must not
// include it: the suite links the SharedCode archive and not this library, so
// a pin reading these symbols would need the test's link line changed, which
// is the same shape as the OpenGL gap in that script.
//
// THE PLAYBACK GRID DRAWS TEN OF THEM, through playbackArtForTile below:
// mono_fold.jpg for the Mono tile, the eight voicing pictures, and
// codec_lossy.jpg for the codec tile. Referencing them is what makes the
// linker pull those images into the AU and VST3. Of the other nine,
// codec_transparent and codec_loudness have cases in codecArtFor that nothing
// calls, and car_speaker, bedroom, small_bar, club_floor, festival_field,
// headphones and studio_monitors are embedded in the library and mapped to
// nothing.

namespace echojay
{

/** One embedded image: the bytes and their length, or nothing. */
struct PlaybackArt
{
    const char* data = nullptr;
    int         size = 0;

    bool isValid() const noexcept { return data != nullptr && size > 0; }
};

/** The picture for a device voicing. None, and the Count sentinel, have none.

    CarDashboard uses car_interior.jpg, the dashboard view; car_speaker.jpg is
    embedded but mapped to nothing yet, as are the room pictures (bedroom,
    small_bar, club_floor, festival_field), headphones and studio_monitors. */
inline PlaybackArt playbackArtFor (PlaybackVoicing v) noexcept
{
    switch (v)
    {
        case PlaybackVoicing::PhoneSpeaker: return { EJPlaybackArt::phone_speaker_jpg, EJPlaybackArt::phone_speaker_jpgSize };
        case PlaybackVoicing::Laptop:       return { EJPlaybackArt::laptop_jpg,        EJPlaybackArt::laptop_jpgSize };
        case PlaybackVoicing::CarDashboard: return { EJPlaybackArt::car_interior_jpg,  EJPlaybackArt::car_interior_jpgSize };
        case PlaybackVoicing::KitchenRadio: return { EJPlaybackArt::kitchen_jpg,       EJPlaybackArt::kitchen_jpgSize };
        case PlaybackVoicing::Earbuds:      return { EJPlaybackArt::earbuds_jpg,       EJPlaybackArt::earbuds_jpgSize };
        case PlaybackVoicing::TvSoundbar:       return { EJPlaybackArt::tv_soundbar_jpg, EJPlaybackArt::tv_soundbar_jpgSize };
        case PlaybackVoicing::BluetoothSpeaker: return { EJPlaybackArt::bt_speaker_jpg,  EJPlaybackArt::bt_speaker_jpgSize };
        case PlaybackVoicing::ClubPA:           return { EJPlaybackArt::club_pa_jpg,     EJPlaybackArt::club_pa_jpgSize };
        case PlaybackVoicing::None:
        case PlaybackVoicing::Count:
            break;
    }
    return {};
}

/** The codec page's three kinds of tile, one picture each. Which preset shows
    which tile is the page's decision, not this file's. */
enum class CodecTile
{
    Transparent,   ///< a codec setting that should be inaudible
    Lossy,         ///< a codec setting whose artefacts are the point of listening
    Loudness       ///< the -14 LUFS normalisation
};

inline PlaybackArt codecArtFor (CodecTile t) noexcept
{
    switch (t)
    {
        case CodecTile::Transparent: return { EJPlaybackArt::codec_transparent_jpg, EJPlaybackArt::codec_transparent_jpgSize };
        case CodecTile::Lossy:       return { EJPlaybackArt::codec_lossy_jpg,       EJPlaybackArt::codec_lossy_jpgSize };
        case CodecTile::Loudness:    return { EJPlaybackArt::codec_loudness_jpg,    EJPlaybackArt::codec_loudness_jpgSize };
    }
    return {};
}

/** The picture a grid tile shows: mono_fold.jpg for Mono, a voicing tile's
    voicing picture, codec_lossy.jpg for the codec tile. Every tile has one.

    Mono is matched on its selection because it is not a voicing: it has no
    PlaybackVoicing value for playbackArtFor to take. */
inline PlaybackArt playbackArtForTile (const PlaybackTile& t) noexcept
{
    switch (t.kind)
    {
        case PlaybackTileKind::CodecRender: return codecArtFor (CodecTile::Lossy);
        case PlaybackTileKind::Live:
            if (t.sim == PlaybackSim::MonoFold)
                return { EJPlaybackArt::mono_fold_jpg, EJPlaybackArt::mono_fold_jpgSize };
            return playbackArtFor (t.voicing);
    }
    return {};
}

/** Decodes an embedded picture, once per process, through juce::ImageCache.

    IMAGECACHE, AND NEVER A FUNCTION-LOCAL static juce::Image. A static Image
    lives until the plugin's binary is unloaded, and if it still owns a GPU or
    OpenGL texture then, freeing it under the Windows loader lock deadlocks the
    host. That was confirmed by a hang dump (HungIn_LoaderLock) and is written
    up at EchoJayLookAndFeel.h:456, drawLogo, and again at PluginEditor.cpp:50,
    getFaderFilmstrip, which chose ImageCache for the same reason. ImageCache
    entries are released during normal teardown, so nothing GPU-backed survives
    to unload. It is also keyed by the data's address, so every editor instance
    shares one decode instead of holding a copy each.

    An invalid entry returns an invalid Image, never a decode of nothing. */
inline juce::Image loadPlaybackArt (const PlaybackArt& art)
{
    if (! art.isValid())
        return {};
    return juce::ImageCache::getFromMemory (art.data, art.size);
}

} // namespace echojay
